apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

managedNodeGroups:
  - name: expense
    instanceTypes: ["t3.medium", "t3.small", "t3.micro"]
    desiredCapacity: 2
    spot: true